"""Kusto emulator / ADX runner logic with the HTTP layer stubbed (no container, no cloud).

The ADX runner is only tested this way until a real cluster is configured; see
docs/verification.md.
"""

from __future__ import annotations

from typing import Any

import pytest

import rosettalog.verify.real.kusto as kusto
from rosettalog.backends.sentinel import SentinelBackend
from rosettalog.verify.real.docker import RealEngineError
from tests.conftest import EXAMPLES, NOW, parse_lsx

ACME = EXAMPLES / "acme_firewall" / "acme_fw.lsx.xml"
LOG = '<134>Mar 14 09:26:53 fw1 x: ts="2026-03-14 09:26:53.120" action=deny src=10.0.0.1'


class FakeHttp:
    def __init__(self, fail_query: bool = False) -> None:
        self.calls: list[tuple[str, dict[str, Any], dict[str, str]]] = []
        self.fail_query = fail_query

    def __call__(self, method, url, body=None, *, headers=None, timeout=120):
        self.calls.append((url, body, dict(headers or {})))
        if url.endswith("/v1/rest/query"):
            if self.fail_query:
                raise RealEngineError("query rejected")
            return {
                "Tables": [
                    {
                        "Columns": [
                            {"ColumnName": "SyslogMessage", "DataType": "String"},
                            {"ColumnName": "SrcIpAddr", "DataType": "String"},
                            {"ColumnName": "EventStartTime", "DataType": "DateTime"},
                            {"ColumnName": "User", "DataType": "String"},
                        ],
                        "Rows": [[LOG, "10.0.0.1", "2026-03-14T09:26:53.12Z", ""]],
                    }
                ]
            }
        return {"Tables": []}


def _result():
    return SentinelBackend().generate(parse_lsx(ACME), {})


def test_session_isolates_samples_in_a_temp_table(monkeypatch) -> None:
    fake = FakeHttp()
    monkeypatch.setattr(kusto, "http_json", fake)
    session = kusto.KustoSession("http://localhost:1", "NetDefaultDB", "test")
    rows = session.extract_batch(_result(), [LOG], now=NOW)
    assert rows[0]["SrcIpAddr"] == "10.0.0.1"
    assert rows[0]["EventStartTime"] == "2026-03-14T09:26:53.120Z"
    assert rows[0]["User"] is None
    csl = [body["csl"] for _, body, _ in fake.calls]
    assert csl[0].startswith(".create table rl_verify_")
    temp = csl[0].split()[2]
    assert csl[1].startswith(f".set-or-append {temp} <| datatable(SyslogMessage:string)")
    assert csl[2].startswith(f"let Syslog = {temp};\n// Generated by rosettalog")
    assert csl[3] == f".drop table {temp} ifexists"
    assert all(body["db"] == "NetDefaultDB" for _, body, _ in fake.calls)


def test_temp_table_is_dropped_even_on_failure(monkeypatch) -> None:
    fake = FakeHttp(fail_query=True)
    monkeypatch.setattr(kusto, "http_json", fake)
    session = kusto.KustoSession("http://localhost:1", "db", "test")
    with pytest.raises(RealEngineError, match="query rejected"):
        session.extract_batch(_result(), [LOG], now=NOW)
    assert fake.calls[-1][1]["csl"].startswith(".drop table rl_verify_")


def test_adx_runner_requires_explicit_configuration(monkeypatch) -> None:
    for var in kusto.ADX_ENV:
        monkeypatch.delenv(var, raising=False)
    runner = kusto.AdxRunner()
    assert "ROSETTALOG_ADX_CLUSTER" in (runner.unavailable_reason() or "")
    monkeypatch.setenv("ROSETTALOG_ADX_CLUSTER", "http://insecure.example")
    monkeypatch.setenv("ROSETTALOG_ADX_DATABASE", "db")
    monkeypatch.setenv("ROSETTALOG_ADX_TOKEN", "tok")
    assert "https" in (runner.unavailable_reason() or "")
    monkeypatch.setenv("ROSETTALOG_ADX_CLUSTER", "https://c.region.kusto.windows.net/")
    assert runner.unavailable_reason() is None
    fake = FakeHttp()
    monkeypatch.setattr(kusto, "http_json", fake)
    with runner.session() as session:
        session.extract_batch(_result(), [LOG], now=NOW)
    url, body, headers = fake.calls[0]
    assert url == "https://c.region.kusto.windows.net/v1/rest/mgmt"
    assert headers["Authorization"] == "Bearer tok"
    assert body["db"] == "db"


def test_kustainer_refuses_arm_hosts(monkeypatch) -> None:
    monkeypatch.setattr(kusto, "docker_available", lambda: None)
    monkeypatch.setattr(kusto, "docker_arch", lambda: "aarch64")
    reason = kusto.KustainerRunner().unavailable_reason() or ""
    assert "x86-64" in reason
    assert "sentinel-adx" in reason
    monkeypatch.setattr(kusto, "docker_arch", lambda: "x86_64")
    assert kusto.KustainerRunner().unavailable_reason() is None


@pytest.mark.parametrize(
    ("value", "expected"),
    [
        ("2026-03-14T09:26:53.12Z", "2026-03-14T09:26:53.120Z"),
        ("2026-03-14T09:26:53.1234567Z", "2026-03-14T09:26:53.123Z"),
        ("2026-03-14T09:26:53Z", "2026-03-14T09:26:53.000Z"),
        (None, None),
    ],
)
def test_kusto_datetime_canonical(value, expected) -> None:
    assert kusto._canonical(value, "DateTime") == expected
